# Generated by Django 4.1.7 on 2023-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
