# Generated by Django 4.1.7 on 2023-03-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
